name: Deploy to Azure Container Apps

on:
  push:
    branches: [ main ]
    paths:
      - 'codemotion-mcp-server/**'
      - 'infra/**'
      - '.github/workflows/deploy-to-azure.yml'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: |
          cd infra
          terraform init
      
      - name: Terraform Plan
        run: |
          cd infra
          terraform plan -out=tfplan \
            -var="github_token=${{ secrets.GITHUB_TOKEN }}"
      
      - name: Terraform Apply
        run: |
          cd infra
          terraform apply -auto-approve tfplan

      - name: Get ACR details
        id: acr
        run: |
          cd infra
          echo "ACR_LOGIN_SERVER=$(terraform output -raw acr_login_server)" >> $GITHUB_ENV
          echo "ACR_USERNAME=$(terraform output -raw acr_admin_username)" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$(terraform output -raw acr_admin_password)" >> $GITHUB_ENV

      - name: Build and push image to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}
      
      - name: Build and push Docker image
        run: |
          cd codemotion-mcp-server
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/codemotion-mcp-server:${{ github.sha }} .
          docker push ${{ env.ACR_LOGIN_SERVER }}/codemotion-mcp-server:${{ github.sha }}
          docker tag ${{ env.ACR_LOGIN_SERVER }}/codemotion-mcp-server:${{ github.sha }} ${{ env.ACR_LOGIN_SERVER }}/codemotion-mcp-server:latest
          docker push ${{ env.ACR_LOGIN_SERVER }}/codemotion-mcp-server:latest

      - name: Update Container App with new image
        run: |
          RESOURCE_GROUP=$(cd infra && terraform output -raw resource_group_name)
          APP_NAME=$(cd infra && terraform output -raw container_app_name)
          
          az containerapp update \
            --name $APP_NAME \
            --resource-group $RESOURCE_GROUP \
            --container-name mcp-server \
            --image ${{ env.ACR_LOGIN_SERVER }}/codemotion-mcp-server:${{ github.sha }}